# Generated by Django 5.2.13 on 2026-05-06 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('theme_tags', models.JSONField(blank=True, default=list)),
                ('transport_mode', models.CharField(blank=True, default='', max_length=50)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_estimated_cost', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('fork_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='routes.route')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='RouteShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='routes.route')),
            ],
            options={
                'db_table': 'route_shares',
            },
        ),
        migrations.CreateModel(
            name='RouteSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_order', models.SmallIntegerField()),
                ('segment_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('segment_cost', models.IntegerField(default=0)),
                ('segment_duration_minutes', models.IntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_spots', to='routes.route')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_spots', to='spots.touristspot')),
            ],
            options={
                'db_table': 'route_spots',
                'constraints': [models.UniqueConstraint(fields=('route', 'sequence_order'), name='unique_route_sequence')],
            },
        ),
    ]
