# Generated by Django 5.2.13 on 2026-05-06 14:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('UNVISITED', '미방문'), ('CERTIFIED', '인증완료'), ('REJECTED', '거부')], default='UNVISITED', max_length=20)),
                ('stay_start_at', models.DateTimeField(blank=True, null=True)),
                ('stay_end_at', models.DateTimeField(blank=True, null=True)),
                ('stay_minutes', models.IntegerField(default=0)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='spots.touristspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visit_logs',
            },
        ),
        migrations.CreateModel(
            name='GpsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('recorded_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gps_logs',
                'indexes': [models.Index(fields=['user', 'recorded_at'], name='idx_gpslog_user_recorded')],
            },
        ),
    ]
