# Generated by Django 5.2.13 on 2026-05-06 14:39

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('theme_tags', models.JSONField(blank=True, default=list)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('entrance_fee', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('avg_review_score', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('avg_cost', models.IntegerField(default=0)),
                ('avg_stay_minutes', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tourist_spots',
            },
        ),
    ]
