# Generated by Django 5.2.14 on 2026-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlaceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('place_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user_rating_count', models.IntegerField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True)),
                ('google_maps_uri', models.TextField(blank=True)),
                ('reviews', models.JSONField(default=list)),
                ('reviews_fetched', models.BooleanField(default=False)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'google_place_cache',
            },
        ),
    ]
